# [5.3. Модель исключений Python. Try, except, else, finally. Модули](https://education.yandex.ru/handbook/python/article/model-isklyuchenij-python-try-except-else-finally-moduli)
## A. Обработка ошибок
Вашему решению будет предоставлена функция func, которая не имеет параметров и результата. Однако во время её исполнения может произойти одна из ошибок: ValueError, TypeError или SystemError.  

Вызовите её, обработайте ошибку и выведите её название. Если ошибка не произойдёт, выведите сообщение "No Exceptions".  

---
```python
try:
    func()
except Exception as e:
    print(type(e).__name__)
else:
    print('No Exceptions')
```

## B. Ломать — не строить
Давайте немного поиграем в «багоюзеров».  

Вашему решению будет предоставлена функция func, которая принимает два позиционных параметра и производит с ними некую математическую операцию.  

Предложите вызов функции, который гарантированно породит ошибку внутри функции.  

**Примечание**  
Если ошибка произойдёт внутри функции, то она будет перехвачена и обработана.  
Если же она произойдет в вашем коде, то программа будет завершена с ошибкой.  

---
```python
try:
    func(1, None)
except BaseException:
    print('Ура! Ошибка!')
```

## C. Ломать — не строить 2
Вашему решению будет предоставлена функция func, которая на этот раз принимает неограниченное число позиционных параметров и производит с ними некую операцию приведения типа.  

Предложите вызов функции, который гарантированно породит ошибку внутри функции.  

**Примечание**  
Если ошибка произойдёт внутри функции, то она будет перехвачена и обработана.  
Если же она произойдет в вашем коде, то программа будет завершена с ошибкой.  

---
```python
class Err:
    def __repr__(self):
        raise Exception


try:
    a = Err()
    func(a)
except BaseException:
    print('Ура! Ошибка!')
```

## D. Контроль параметров
Напишите функцию only_positive_even_sum, которая принимает два параметра и возвращает их сумму.  

Если один из параметров не является целым числом, то следует вызвать исключение TypeError.  
Если один из параметров не является положительным чётным числом, то следует вызвать исключение ValueError.  

**Примечание**  
Ваше решение должно содержать только функции.  
В решении не должно быть вызовов требуемых функций.  

---
```python
def only_positive_even_sum(a, b):
    if not isinstance(a, int) or not isinstance(b, int):
        raise TypeError
    if not (a > 0 and not a % 2) or not (b > 0 and not b % 2):
        raise ValueError
    return a + b
```

## E. Слияние с проверкой
Когда-то вы уже писали функцию merge, которая производит слияние двух отсортированных кортежей.  

Давай-те её немного переработаем.  

Введём систему проверок:  

- если один из параметров не является итерируемым объектом, то вызовите исключение StopIteration;  
- если значения входных параметров содержат «неоднородные» данные, то вызовите исключение TypeError;  
- если один из параметров не отсортирован, то вызовите исключение ValueError.  

Проверки следует проводить в указанном порядке.  

Если параметры прошли все проверки, верните итерируемый объект, являющийся слиянием двух переданных.  

**Примечание**  
В решении не должно быть вызовов требуемых функций.  

---
```python
def merge(fl, sl): 
    if not hasattr(fl, '__iter__') or not hasattr(sl, '__iter__'):
        raise StopIteration
    if not (all(isinstance(i, type(fl[0])) for i in fl) and all(isinstance(i, type(fl[0])) for i in sl)):
        raise TypeError
    if list(fl) != sorted(fl) or list(sl) != sorted(sl):
        raise ValueError    
    return sorted(list(list(fl) + list(sl)))
```

## F. Корень зла 2
В одной из первых лекций вы уже решали задачу о поиске корней уравнения. Давайте модернизируем её.  

Напишите функцию find_roots, принимающую три параметра: коэффициенты уравнения и возвращающую его корни в виде кортежа из двух значений.  

Так же создайте два собственных исключения NoSolutionsError и InfiniteSolutionsError, которые будут вызваны в случае отсутствия и бесконечного количества решений уравнения соответственно.  

Если переданные коэффициенты не являются рациональными числами, вызовите исключение TypeError.  

**Примечание**  
В решении не должно быть вызовов требуемых функций.  

---
```python
class InfiniteSolutionsError(Exception):
    pass


class NoSolutionsError(Exception):
    pass


def find_roots(a, b, c):
    if sum(1 for i in (a, b, c) if type(i) not in (int, float)):
        raise TypeError
    elif not a and not b and not c:
        raise InfiniteSolutionsError
    elif not a and not b and c or b ** 2 < 4 * a * c:
        raise NoSolutionsError
    elif b ** 2 == 4 * a * c:
        return -b / (2 * a), -b / (2 * a)
    elif not a:
        return -c / b
    else:
        roots = [(-b - (b ** 2 - 4 * a * c) ** 0.5) / (2 * a), (-b + (b ** 2 - 4 * a * c) ** 0.5) / (2 * a)]
        roots.sort()
        return roots[0], roots[1]
```

## G. Валидация имени
При регистрации в различных сервисах пользователи вводят большое количество информации. Правильное заполнение полей — важная часть работы программы, поэтому формы снабжают системами валидации данных.  

Напишите функцию name_validation, которая принимает один позиционный аргумент — фамилию или имя.  

Если параметр не является строкой, то вызовите исключение TypeError.  

А также разработайте собственные ошибки:  

- CyrillicError — вызывается, если значение не состоит только из кириллических букв;  
- CapitalError — вызывается, если значение не начинается с заглавной буквы или найдена заглавная буква не в начале значения.  

Обработка ошибок должна происходить в порядке, указанном в задании.  

В случае успешного выполнения, функция должна вернуть переданный параметр без изменений.  

**Примечание**  
В решении не должно быть вызовов требуемых функций.  

---
```python
class CyrillicError(Exception):
    pass


class CapitalError(Exception):
    pass


def name_validation(name):
    if not isinstance(name, str):
        raise TypeError
    if any(ord(i.lower()) not in range(ord('а'), ord('я') + 1) if i.lower() != 'ё' else False for i in name):
        raise CyrillicError
    if name != name.lower().capitalize():
        raise CapitalError
    return name
```

## H. Валидация имени пользователя
Продолжим реализацию системы валидации.  

Напишите функцию username_validation, которая принимает один позиционный аргумент — имя пользователя:  

Если параметр не является строкой, то вызовите исключение TypeError.  

А также разработайте собственные ошибки:  

- BadCharacterError — вызывается, если значение состоит не только из латинских букв, цифр и символа нижнего подчёркивания;  
- StartsWithDigitError — вызывается, если значение начинается с цифры.  

Обработка ошибок должна происходить в порядке, указанном в задании.  

В случае успешного выполнения, функция должна вернуть переданный параметр без изменений.  

**Примечание**  
В решении не должно быть вызовов требуемых функций.  

---
```python
class BadCharacterError (Exception):
    pass


class StartsWithDigitError(Exception):
    pass


def username_validation(name):
    if not isinstance(name, str):
        raise TypeError
    if any(ord(i.lower()) not in range(ord('a'), ord('z') + 1) and not i.isdigit() and i != '_' for i in name):
        raise BadCharacterError
    if name[0].isdigit():
        raise StartsWithDigitError
    return name
```

## I. Валидация пользователя
Используйте две предыдущих функции валидации и напишите функцию user_validation, которая принимает именованныеаргументы:  

- last_name — фамилия;  
- first_name — имя;  
- username — имя пользователя.  

Если функции был передан неизвестный параметр или не передан один из обязательных, то вызовите исключение KeyError.  

Если один из параметров не является строкой, то вызовите исключение TypeError.  

Обработка данных должна происходить в порядке: фамилия, имя, имя пользователя.  

Если поле заполнено верно, функция возвращает словарь с данными пользователя.  

**Примечание**  
В решении не должно быть вызовов требуемых функций.  

---
```python
class CyrillicError(Exception):
    pass


class CapitalError(Exception):
    pass


class BadCharacterError (Exception):
    pass


class StartsWithDigitError(Exception):
    pass


def name_validation(name):
    if not isinstance(name, str):
        raise TypeError
    if any(ord(i.lower()) not in range(ord('а'), ord('я') + 1) if i.lower() != 'ё' else False for i in name):
        raise CyrillicError
    if name != name.lower().capitalize():
        raise CapitalError
    return name


def username_validation(name):
    if not isinstance(name, str):
        raise TypeError
    if any(ord(i.lower()) not in range(ord('a'), ord('z') + 1) and not i.isdigit() and i != '_' for i in name):
        raise BadCharacterError
    if name[0].isdigit():
        raise StartsWithDigitError
    return name


def user_validation(**kwargs):
    if any(i not in ['last_name', 'first_name', 'username'] for i in kwargs) or len(kwargs) > 3:
        raise KeyError
    if any(not isinstance(i, str) for i in kwargs):
        raise TypeError
    return {'last_name': name_validation(kwargs['last_name']),
            'first_name': name_validation(kwargs['first_name']),
            'username': username_validation(kwargs['username'])}
```

## J. Валидация пароля
После того как пользователь ввёл свои данные в требуемом формате, можно позаботиться и о пароле.  

Напишите функцию password_validation, которая принимает один позиционный параметр — пароль, и следующие именованные параметры:  

- min_length — минимальная длина пароля, по умолчанию 8;  
- possible_chars — строка символов, которые могут быть в пароле, по умолчанию латинские буквы и цифры;  
- at_least_one — функция возвращающая логическое значение, по умолчанию str.isdigit.  

Если переданный позиционный параметр не является строкой, вызовите исключение TypeError.  

А так же реализуйте собственные исключения:  

- MinLengthError — вызывается, если пароль меньше заданной длины;  
- PossibleCharError — вызывается, если в пароле используется недопустимый символ;  
- NeedCharError — вызывается, если в пароле не найдено ни одного обязательного символа.  

Проверка условий должна происходить в порядке указанном в задании.  

Так как, хороший разработчик никогда не хранит пароли в открытом виде, функция, в случае успешного завершения, возвращает хеш пароля. Для этого воспользуйтесь функцией sha256 из пакета hashlib и верните его шестнадцатеричное представление.  

**Примечание**  
В решении не должно быть вызовов требуемых функций.

---
```python
from hashlib import sha256


class MinLengthError(Exception):
    pass


class PossibleCharError(Exception):
    pass


class NeedCharError(Exception):
    pass


def password_validation(psswrd, min_length=8,
                        possible_chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
                        at_least_one=str.isdigit):
    if not isinstance(psswrd, str):
        raise TypeError
    if len(psswrd) < min_length:
        raise MinLengthError
    if any(i not in possible_chars for i in psswrd):
        raise PossibleCharError
    if not (any(at_least_one(i) for i in psswrd)):
        raise NeedCharError

    return sha256((psswrd).encode('utf-8')).hexdigest()
```
